CREATE DATABASE "yii2" ENCODING 'UTF8' LC_COLLATE = 'RU_RU.UTF-8' LC_CTYPE = 'RU_RU.UTF-8';
CREATE DATABASE "yii2_test" ENCODING 'UTF8' LC_COLLATE = 'RU_RU.UTF-8' LC_CTYPE = 'RU_RU.UTF-8';
GRANT ALL PRIVILEGES ON DATABASE "yii2" TO "yii2_user";
GRANT ALL PRIVILEGES ON DATABASE "yii2_test" TO "yii2_user";
